name: Test Automatisation

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Vérifier Node.js
        run: node --version

      - name: Installer les dépendances
        run: npm install

      - name: Lancer le build
        run: npm run build
